### ISSUE TITLE
Add PHP example

### ISSUE THREAD

**Issue by mgkimsal** [1brc/1brc.github.io#3]
This blog post details out a PHP approach to the 1brc with a good walk through of step by step iterative improvements: https://dev.to/realflowcontrol/processing-one-billion-rows-in-php-3eg0

**Comment by realFlowControl** [comment]
Hey @jcbhmr 🖖 
I added a GitHub Repo with the PHP solution: https://github.com/realFlowControl/1brc
Would be awesome if you could add it, I could also provide you a PR in case it helps.
